spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    include-message: always

custom:
  check:
    expired:
      on-creation: true


